---
- hosts: bacula-clients
  user: ansible
  sudo: True
  tasks:
    - name: Install gcc
      yum: name=gcc state=installed
    - name: Install glibc
      yum: name=glibc state=installed
    - name: Install make
      yum: name=make state=installed
    - name: Install python
      yum: name=python state=installed
