---
- hosts: CentOS
  user: ansible
  sudo: yes
  tasks:
  
  - name: get epel-repo rpm RHEL6
    get_url: dest=/tmp/epel-release.rpm  url=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
    when: ansible_os_family == 'CentOS' and ansible_lsb.major_release|int == 6
  
  - name: get epel-repo rpm RHEL7
    get_url: url='http://mirror.web24.net.au/epel/beta/7/x86_64/epel-release-7-0.2.noarch.rpm' dest=/tmp/epel-release.rpm force=yes
    when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

  - name: install a file
    yum: name=/tmp/epel-release.rpm state=installed
