- hosts: all
  user: ansible
  sudo: true
  tasks:
    - name: Open the correct IPTables ports
      lineinfile: dest=/etc/sysconfig/iptables
                  regexp="^-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT$"
                  line="-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT"
                  insertafter="^:OUTPUT ACCEPT \[\d*:\d*\]$"
      with_items:
        - { protocol: tcp, port: 80 }
        - { protocol: tcp, port: 22 }
        - { protocol: udp, port: 53 }
        - { protocol: udp, port: 123 }
        - { protocol: tcp, port: 5666 }
      notify:
        - restart iptables

  handlers:
      - name: restart iptables
        action: service name=iptables state=restarted
