---
- hosts: mysql
  user: ansible
  sudo: yes
  tasks:

  - name: Create mysql DB
    mysql_db: name={{ item }}-svblogs encoding=utf8 collation=utf8_bin state=present
    with_items:
    - qa
    - dev



  - name: Create mysql DB
    mysql_user: name=svblogs password=svblogs priv='svblogs.*:ALL/qa-svblogs.*:ALL/dev-svblogs.*:ALL' host={{ item }} 
    with_items:
    - 127.0.0.1
    - '%'
    - ::1
    - localhost

