---
- hosts: mysql
  user: ansible
  sudo: yes
  tasks:

  - name: Install Python mysql bindings
    yum: name=MySQL-python state=installed

  - name: Install MySQL
    yum: name={{ item }}
    with_items:
    - mysql-community-common
    - mysql-community-server
    - libselinux-python

  - name: Start the MySQL service
    service: name=mysqld state=started enabled=yes

  - name: Create mysql user
    mysql_user: name=root password=rimmer priv='*.*:ALL,GRANT' host={{ item }} 
    with_items:
    - $ansible_hostname
    - 127.0.0.1
    - '%'
    - ::1
    - localhost

  - name: copy my.cnf file with root password credentials
    template: src=templates/root/my.cnf dest=/root/.my.cnf owner=root mode=0600

  - name: remove the MySQL test database
    action: mysql_db db=test state=absent
