---
- hosts: savbatv2
  user: ansible
  sudo: true
  vars:
    PROJECT_HOME: "/var/www/qa-savbat-v2"
    ansible_python_interpreter: "/usr/local/python-2.7.6/bin/python"

  tasks:
   - name: Install Python Module
     pip: requirements="{{PROJECT_HOME}}/savbat_v2/misc/software/requirements.txt" virtualenv={{ PROJECT_HOME }}
