---
- hosts: savbatv2.spatialvision.com.au
  user: ansible
  sudo: true
  tasks:
   - name: Ensure Latest system updates are installed.
     apt: update_cache=yes
   - name: We need xz-utils to unpack the python tarball.
	 apt: install xz-utils
   - name: Prepare the environment to build Python.
     command: chdir /usr/local
     command: mkdir python
     command: mkdir python-2.7.6
     command: chdir /usr/local/python
   - name: Download the Python-2.7.6 source tree
	 command: wget -c https://www.python.org/ftp/python/2.7.6/Python-2.7.6.tar.xz
	 command: tar xvJf Python-2.7.6.tar.xz
   - name: Build the Python
   	command: chdir Python-2.7.6
   	command: ./configure --prefix=/usr/local/python-2.7.6
   	command: make
   	command: make install
