---
- hosts: all
  user: root
  vars: 
    createuser: 'ansible'
    createpassword: 'rimmer'
  tasks:
  - name: install libselinux-python
    yum: name=libselinux-python state=present
  - name: Setup | create user
    command: useradd -n {{ createuser }} creates=/home/{{ createuser }}
    sudo: true
 
  - name: Setup | set user password
    shell: usermod -p $(echo '{{ createpassword }}' | openssl passwd -1 -stdin) {{ createuser }}
    sudo: true
 
  - name: Setup | authorized key upload
    authorized_key: user={{ createuser }}
      key="{{ lookup('file', '~jonnewson/.ssh/id_rsa.pub') }}"
      path='/home/{{ createuser }}/.ssh/authorized_keys'
      manage_dir=yes
    sudo: true
 
  - name: Sudoers | update sudoers file and validate
    lineinfile: "dest=/etc/sudoers
      insertafter=EOF
      line='{{ createuser }} ALL=(ALL) NOPASSWD: ALL'
      regexp='{{ createuser }} ALL=(ALL) NOPASSWD: ALL'
      state=present"
    sudo: true
